import {test} from 'node:test';
import assert from 'node:assert/strict';
import {inspectRecord,parseInspection,play,commit,crashResult,sha256Hex,generateKeyPair,signRecord} from '../dist/index.js';
const seed='5c1f7d3e8a2b4c6d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d';
async function record(game='dice',params={}){const seeds={serverSeed:seed,clientSeed:'galabet',nonce:42};const out=await play({game,params,...seeds});return {spec:'GFS/1.0',profile:'single-player',game,params,...seeds,commitment:(await commit(seed)).commitment,cursor:out.cursor,result:out.result,at:0};}
test('all nine game records reproduce',async()=>{for(const [g,p] of [['dice',{}],['roulette',{}],['limbo',{houseEdge:.01}],['plinko',{rows:16}],['mines',{mines:3}],['keno',{draws:10}],['wheel',{segments:10}],['blackjack',{decks:1}],['hilo',{decks:1}]])assert.equal((await inspectRecord(await record(g,p))).status,'matches',g);});
test('changed outcome identifies first differing field',async()=>{const r=await record('plinko',{rows:16});r.result.path[2]=r.result.path[2]===0?1:0;const report=await inspectRecord(r);assert.equal(report.status,'mismatch');assert.match(report.difference,/path\[2\]/);});
test('commitment and cursor tampering are separate checks',async()=>{const r=await record();r.commitment='0'.repeat(64);r.cursor=99;const out=await inspectRecord(r);assert.equal(out.status,'mismatch');assert.equal(out.checks.find(c=>c.name==='Commitment').state,'mismatch');assert.equal(out.checks.find(c=>c.name==='Cursor').state,'mismatch');assert.equal(out.checks.find(c=>c.name==='Outcome').state,'matches');});
test('unrevealed seed and calculation-only mode remain incomplete',async()=>{const r=await record();delete r.serverSeed;assert.equal((await inspectRecord(r)).status,'incomplete');const raw=await record();delete raw.result;delete raw.commitment;assert.equal((await inspectRecord(raw)).status,'incomplete');});
test('reject unsafe numbers, incompatible params and unsupported profiles',async()=>{const r=await record();for(const change of [{nonce:2**53},{nonce:-1},{params:{decks:100000}},{profile:'other'},{spec:'GFS/3.0'},{clientSeed:'a:b'},{game:'toString'}])await assert.rejects(inspectRecord({...r,...change}));});
test('bounded JSON parser rejects invalid, oversized and deep data',()=>{for(const s of ['null','[]','{','{"x":"'+'a'.repeat(65536)+'"}','{"x":'+ '['.repeat(15)+'0'+']'.repeat(15)+'}'])assert.throws(()=>parseInspection(s));});
test('Crash fixture checks endpoint and adjacent chain link',async()=>{const r={gameHash:seed,salt:'public-fixture',houseEdge:.01,previousHash:await sha256Hex(seed),result:await crashResult(seed,'public-fixture',.01)};assert.equal((await inspectRecord(r)).status,'matches');assert.equal((await inspectRecord({...r,previousHash:'0'.repeat(64)})).status,'mismatch');});
test('Flight checks endpoint but does not authenticate receipt',async()=>{const r={id:'public-fixture',gameHash:seed,salt:'flight-example',houseEdge:.01,commitment:await sha256Hex(seed),result:await crashResult(seed,'flight-example',.01),payout:999999};const out=await inspectRecord(r);assert.equal(out.status,'matches');assert.match(out.note,/do not authenticate/);});
test('signed record and tampered signature',async()=>{const {secretKey}=await generateKeyPair();const r=await signRecord(await record(),secretKey);assert.equal((await inspectRecord(r)).checks.find(c=>c.name==='Signature').state,'matches');assert.equal((await inspectRecord({...r,signature:'0'.repeat(128)})).status,'mismatch');});
test('beacon checks cannot silently pass',async()=>{assert.equal((await inspectRecord({...await record(),beacon:{source:'drand',ref:'1',value:'0'}})).status,'incomplete');});
